import pandas as pd
df = pd.read_csv("CarbonEmission.csv")
print(df.head())
print("\nDataset Shape:")
print(df.shape)
print("\nDataset Information:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
print("\nShape After Removing Duplicates:")
print(df.shape)
df["Vehicle Type"] = df["Vehicle Type"].fillna("None")
print("\nMissing Values After Filling:")
print(df.isnull().sum())